---
version: "3"

tasks:
  oas-download:
    desc: Download OpenAPI specification
    cmds:
      - curl -o openapi.yaml https://raw.githubusercontent.com/inference-gateway/inference-gateway/refs/heads/main/openapi.yaml

  lint:
    desc: Lint the code
    cmds:
      - black inference_gateway/ tests/

  test:
    desc: Run tests
    cmds:
      - pytest tests/ -v

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - ptw tests/ -- -v

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - pytest tests/ -v --cov=inference_gateway --cov-report=term-missing

  test:debug:
    desc: Run tests with debugger enabled
    cmds:
      - pytest tests/ -v --pdb

  clean:
    desc: Clean up
    cmds:
      - rm -rf inference_gateway.egg-info dist .pytest_cache inference_gateway/__pycache__ tests/__pycache__ .coverage
