---
version: "3"

tasks:
  oas-download:
    desc: Download OpenAPI specification
    cmds:
      - curl -o openapi.yaml https://raw.githubusercontent.com/inference-gateway/inference-gateway/refs/heads/main/openapi.yaml

  lint:
    desc: Lint the code
    cmds:
      - black inference_gateway/ tests/

  test:
    desc: Run tests
    cmds:
      - pytest tests/

  clean:
    desc: Clean up
    cmds:
      - rm -rf inference_gateway.egg-info dist .pytest_cache
